<a href="https://colab.research.google.com/github/Snoveedh/DeepLearning_Repo/blob/Perceptron/Back_propagation_ownCode_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import pandas as pd

In [9]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa','profile_score','lpa'])

In [10]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [11]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [12]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                      │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.get_weights()

[array([[-1.0215192, -1.1209605],
        [ 0.9069289,  1.0584463]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.39458585],
        [ 1.1231545 ]], dtype=float32),
 array([0.], dtype=float32)]

In [14]:
new_weights = [
               np.array([[0.1, 0.1],[0.1,0.1]], dtype=np.float32),
               np.array([0.,0.],dtype=np.float32),
               np.array([[0.1],[0.1]], dtype=np.float32),
               np.array([0.],dtype=np.float32)
               ]

In [15]:
model.set_weights(new_weights)

In [16]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [17]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [18]:
model.fit(df.iloc[:, 0:-1].values,df['lpa'].values, epochs=75, verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 22.6985  
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.1989 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.0476 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 28.5474 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 30.3726 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.0273 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.1068 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.0592 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 31.0374 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 27.8034 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 21.5205 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25.3565 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 18.9018 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 26.5923 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.5095
Epoch 16/75
4/4 ━━━

In [19]:
model.get_weights()

[array([[0.37343058, 0.37343058],
        [0.36573523, 0.36573523]], dtype=float32),
 array([0.27228418, 0.27228418], dtype=float32),
 array([[0.37291628],
        [0.37291628]], dtype=float32),
 array([0.20481943], dtype=float32)]